### ISSUE TITLE
请问如何监控多个scrapy项目以及多个spider?

### ISSUE THREAD

**Issue by micromanchg** [ioiogoo/scrapy-monitor#2]
请问如何监控多个scrapy项目以及多个spider?

**Comment by ioiogoo** [comment]
春节回老家了，网络不是很方便。
1. 多个scrapy项目跟单个项目监控原理一样，只是效果展示的时候需要将多个图表汇总到一个前端页面上来。
2. 同一项目下多个spider这种情况我不是太清楚，粗略看了下文档，好像同一个项目下的统计情况只有汇总结果，并没有分各个spider的stats。实际情况你可以查看下[这里](https://github.com/ioiogoo/scrapy-monitor/blob/master/visiter/visiter/monitor/statscol.py#L22)，所有的状态信息全部保存在`spider.crawler.stats.get_stats()`里面，将里面数据打印出来看下有没有分各个spider的状态信息。

**Comment by micromanchg** [comment]
谢谢。
