### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by pysc** [ioiogoo/scrapy-monitor#4]
报错原因:python版本问题
3.6及以上在 monitor/app.py 中加一句话:
    result = current_app.r.lrange(key, -POINTLENGTH, -1)[::POINTINTERVAL]
    result = [str(i, encoding="utf8") for i in result] # python3.6以下注释掉
    if not current_app.spider_is_run:
         .......

**Comment by pysc** [comment]
thats right

**Comment by ioiogoo** [comment]
sorry, I can't understand you. Please show me the code and error info clearly or I will close this issue, thanks!

**Comment by pysc** [comment]
您分享的这份代码 在python3.6及以上版本会报如上错误(Object of type 'bytes' is not JSON serializable),需在app.py中处理一下(如上方式测试可行)

**Comment by ioiogoo** [comment]
之前的代码用的是python2.7，没有考虑到python3的兼容性，如果有需要用到python3，自己改下就好了。

如果没有其他困难的话，请关闭这个问题，谢谢。
